apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chart.fullname" . }}
  namespace: {{ include "kafka-chart.namespace" . }}
  labels:
    {{- include "kafka-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chart.fullname" . }}-headless
  namespace: {{ include "kafka-chart.namespace" . }}
  labels:
    {{- include "kafka-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.headless.port }}
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka-chart.selectorLabels" . | nindent 4 }}
