apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chart.fullname" . }}-zookeeper
  namespace: {{ include "kafka-chart.namespace" . }}
  labels:
    {{- include "kafka-chart.labels" . | nindent 4 }}
    component: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    {{- include "kafka-chart.selectorLabels" . | nindent 4 }}
    component: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chart.fullname" . }}-zookeeper-headless
  namespace: {{ include "kafka-chart.namespace" . }}
  labels:
    {{- include "kafka-chart.labels" . | nindent 4 }}
    component: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: peer
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: leader-election
  selector:
    {{- include "kafka-chart.selectorLabels" . | nindent 4 }}
    component: zookeeper
