# Default values for kafka-ui-chart
# This is a YAML-formatted file

replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  pullPolicy: IfNotPresent
  tag: "4.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kafka-ui.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Kafka UI Configuration
kafkaUi:
  # Kafka cluster configuration
  clusterName: kafka-cluster
  bootstrapServers: kafka-kafka-chart-headless.kafka.svc.cluster.local:9093
  securityProtocol: PLAINTEXT
  
  # Application configuration
  serverPort: 8080
  loggingLevel: INFO
  dynamicConfigEnabled: true
