services:
  starterkit:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: starterkit
    networks:
      - starterkit-network
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=starterkit
      - POSTGRES_USER=starterkit
      - POSTGRES_PASSWORD=starterkit123
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    container_name: starterkit-postgres
    networks:
      - starterkit-network
    environment:
      - POSTGRES_DB=starterkit
      - POSTGRES_USER=starterkit
      - POSTGRES_PASSWORD=starterkit123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U starterkit -d starterkit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  starterkit-network:
    driver: bridge
