{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-chart.fullname" . }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  postgres-user: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.database | b64enc | quote }}
{{- end }}
